# Generated by Django 4.0.6 on 2023-07-22 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_memes_tagged_memes_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
