# Generated by Django 4.0.6 on 2023-07-22 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tags_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
