# Generated by Django 4.0.6 on 2023-07-24 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_memes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='created_by',
            field=models.ForeignKey(default='accounts.CustomUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
