# Generated by Django 4.0.6 on 2023-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tags_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='meme_tagged',
            field=models.BigIntegerField(default=0),
        ),
    ]
