# Generated by Django 4.0.6 on 2023-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tags_meme_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='comments',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='memes',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
